eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
server:
  port: 8765
  context-path: /service-feign
spring:
  application:
    name: service-feign

service:
  hi: service-hi
